---
- hosts: build
  become: yes
  tasks:
    - name: Update the system
      yum:
        name: "*"
        state: latest

    - name: Install Java, Maven and Git
      yum:
        name:
          - java-1.8.0-openjdk-devel
          - maven
          - git
        state: present
